# This bot created for easy to find the media files from your chennal with theire captions
    # Example :- you have a channle which has many media like photos ,videos ,files ,audio or else
    #            Now you want a specific file without any extra use of time
    #            Then simply send the name and bot forward the similar captions file in the bot chat
    #            then you can pic one 
    # Example Channels :- movie channels ,wallpaper channels ,....,etc
# This code has been generated by Om Lathiya


# line numbers for replace 
                            # Line : 19 Your Bot token
                            # Line : 20 Your channel id or username


import telebot
import json
import os

TOKEN = "<|Your_Bot_Token|>"
CHANNEL_ID = "<|Your channel user name or channel id|>"

DATA_FILE = "data.json"
RESTRICT_TO_CHANNEL = True

bot = telebot.TeleBot(TOKEN)

def load_data():
    if os.path.exists(DATA_FILE):
        try:
            with open(DATA_FILE, "r") as file:
                return json.load(file)
        except json.JSONDecodeError:
            return []
    return []

def save_data(data):
    with open(DATA_FILE, "w") as file:
        json.dump(data, file, indent=4)

media_store = load_data()

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    bot.reply_to(message, "👋 Hi! Send a keyword and I’ll search for media related to it.\n"
                          "Example: `cat`, `pic 01`, `sunflower`, etc.\n\n"
                          "✅ Make sure I'm added as an **admin** to your channel to capture media!",
                 parse_mode="Markdown")

@bot.channel_post_handler(content_types=['photo', 'video', 'document'])
def store_media(message):
    if RESTRICT_TO_CHANNEL and message.chat.id != CHANNEL_ID:
        return

    if not message.caption:
        return

    media_info = {
        "caption": message.caption,
        "type": message.content_type,
        "file_id": None
    }

    if message.content_type == 'photo':
        media_info["file_id"] = message.photo[-1].file_id
    elif message.content_type == 'video':
        media_info["file_id"] = message.video.file_id
    elif message.content_type == 'document':
        media_info["file_id"] = message.document.file_id

    media_store.append(media_info)
    save_data(media_store)

    print(f"[+] Stored {media_info['type']} - {media_info['caption']}")

@bot.message_handler(func=lambda message: True)
def send_stored_media(message):
    query = message.text.lower()
    found = False

    for item in media_store:
        if query in item['caption'].lower():
            if item["type"] == "photo":
                bot.send_photo(message.chat.id, item["file_id"], caption=item["caption"])
            elif item["type"] == "video":
                bot.send_video(message.chat.id, item["file_id"], caption=item["caption"])
            elif item["type"] == "document":
                bot.send_document(message.chat.id, item["file_id"], caption=item["caption"])
            found = True

    if not found:
        bot.reply_to(message, "❌ No media found with that keyword.")

print("🤖 Bot is running...")
bot.infinity_polling()
